groups:
- name: db-connection-alerts
  rules:
    - alert: HighDBConnectionUsage
      expr: hikaricp_connections_active / hikaricp_connections_max > 0.8
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Uso alto de conexões com o banco"
        description: "Mais de 80% das conexões do pool HikariCP estão em uso no job {{ $labels.job }}."

    - alert: DBConnectionWaits
      expr: hikaricp_connections_pending > 5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Muitas requisições aguardando conexão com o banco"
        description: "Mais de 5 threads aguardando conexão no HikariCP ({{ $labels.instance }})."
