name: CI/CD Delivery API

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build e Testes (unitários + integração)
        run: mvn clean verify --file ./delivery-api/pom.xml

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/delivery-api:latest ./delivery-api
          docker push ${{ secrets.DOCKER_USERNAME }}/delivery-api:latest

  deploy-homolog:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy para Homologação via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOMOLOG_SERVER_HOST }}
          username: ${{ secrets.HOMOLOG_SERVER_USER }}
          key: ${{ secrets.HOMOLOG_SERVER_SSH_KEY }}
          script: |
            cd ~/delivery-api-robson/delivery-api
            docker compose pull
            docker compose up -d
            docker image prune -f

      - name: Validar Deploy Homologação
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOMOLOG_SERVER_HOST }}
          username: ${{ secrets.HOMOLOG_SERVER_USER }}
          key: ${{ secrets.HOMOLOG_SERVER_SSH_KEY }}
          script: |
            echo "Validando status da aplicação..."
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health || echo "000")
            if [ "$STATUS_CODE" -ne 200 ]; then
              echo "Erro: aplicação não respondeu com HTTP 200"
              exit 1
            else
              echo "Aplicação funcionando corretamente com HTTP 200"
            fi

  deploy-prod:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy via SSH no servidor produção
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/Documents/delivery-api-robson/delivery-api
            docker compose pull
            docker compose up -d
            docker image prune -f
